#!/usr/bin/php -q
<?php //0044f
// 0 @Ioncube;
// 
// Call Recording Report 17.0.3.8
// Copyright 2024 by Sangoma Technologies Inc., All rights reserved
// 
// By installing, copying, downloading, distributing, inspecting or using
// the materials provided herewith, you agree to all of the terms of use as
// outlined in our End User Agreement which can be found and reviewed at
// https://www.freepbx.org/legal/
// 
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPuvwLsqNnwj2xil2Ja7+sIERfP1sjqWCw82uC64nTrs82ONXcZJsBYt9U4Cu4Q0jscZLRW8i
+Dfx3dkUy7+FB2luVNdRbP0xnnwvfhGPiXi5tX3v6590zMh1Zh9/Ay/OSoaEueqdo4BBgfQ23iMv
UgkM9+OT/o1ZtwiNqsMC/rDRMYhDCrZSzwu0cm3Cx8VsW9ErH7+f/4Ja1SBc2ArEEsZ83hufXdod
BYnFUtZmxjGzqCOUlgN0Now3aOeDwzejQh+fqMkQ36Zxa9e2bMdqAaJOglXgo74cL2MxrkyFt0Rl
DmXIRMvp2IlQl7BrJz0qvAWBfu83mu0Qx/nTTrsTuAzwvBmUn/pM8AlxtSIw85OI+YR3PqGWrgKP
tnlxK7KBWt4ORZe1Q6eCm5e1YX7tU8yusHenzFqdsnaozxOQpoc3aag1mmWxWr2+QIO31+SzNHcI
0Z+H+4JiAHSUno4txFrycpwvd1TFNdPxhUVcNdZlKBJSXTCT8g8Wx/TkbAVSpewGmdUrr+vFKIMD
sMqMRwuQ78FagRrp4klN2koqh0P8tAKuMODD5U/r4aFsOtL/BCOoRAXRBgMNKAh++1E3V37nSi6c
DsVUyn8TiPAAAIvglL7dVqEL5J+/fv2qkEcYs/uBLeoN2XCGLnPVa7YYpMdQkUuSyonYEfFYDWsX
uSDPbamGyKh/b1vJbdq546zEB8nOR6z3kBNLk7qAKkg52mKNOrlzLVQveaG/hFq5UDU+9nmIHG0N
J265obctv0HcW5iMoWoa9gHYABoRq3AEMBCgRIg9oAnGQoxkEBYbNQiRHOqW2K8S3MDGPqySSt+N
5zpvVYKMBvDT5Q41hkCo3aAWGdw98Ev3++uqWeA74TFvzJc1c1JZSVckUdVhutWc4QsMTm8LpnAM
PBiwe4Gpm4IpgkcaWrRHTDZcwUNEgl5bGSzPG2SmGt+1KzafY1iM/c+eR/pJvQAyv1+h8wyH1Xvx
pw1ybw6R4nsLs2RfTBHOmm1tCS3pXUAZX+unfxOpxiTAc5OgRDXn8w03e6cvVSdst1EcDXR9h9ee
uSX7jQ7YuENU4PljRvQ5FVZ1sqTtz5KJ62PffkX0UsjRATnL+VpY7MO+WF0u7jz8sAUXbLnY7+40
eEJ7fj9Dxtua/PeGVC6CLsCOevhkxXQT6Pr9V14DdUVXs5StbvBijXpTAPDAJFLrMQ4Y1IDH5rPz
XQJUTR3sM0waHlI2URfkPZIeRNyJEMZY2jSxjBJRX9KtnQQz0aWk7ZcHoZO+U+S54QdFxaYRGMIM
+JwjCLR9eqLR9oN5Fkp430MhroLAknn6maekEy2RdfqUScXTi0FafkViZQHHXOlwIsKq/z8lvp30
dKxcBjnxzLXSCymgWiECYSVH8H8xg74Gdo2G99MXaWYMrmCw+jZ0gh5fIYCN5eR2ny8NLGDnouuC
huE/yxdj1KBv5HrBUeagCqTXks91/2ja/4bGyb8YIz4pi1lz2mQr1GCQNm5+mjOqrD8dU2+BXAWj
f57a3gZ1fxOuKj9cj81/1sBGBmasLeHT1F/l73ZLAG713C7qVYKcBAuOD9T1gDVbxIYlROgonWVR
Tde7QXXKoS6aSZSMI2yrtsZsMFkfGjxrdelXXfCJk1C7GUdIJh3b5gG70eN4qd4H8dyEKhv17laV
GPqSwfSf+5dMsVsI17eoe2K0UiJDrr6bmr6pHoqJmhZJ1bc2uX930Bnga8g9ZczW7OCe4FtTPkzy
HlyBLk61K5IzSWVAIVf4GNjRoic9aS2DMSupKqLmI+kE3+sAaDjuHu89xqL8gSD9whhdyyBM5lhh
E9SIbWiGs4syBJhUGx6FiL86yeqrlgKE/TgBU8gAFZyGQVVNlmsnJSgSkBZtaTpekXYarCNPnXdl
Yd8wa57/H2woEI7ltPe0/V+faNGWD/cJdmj8zbrna0iJzN+qj5xNDPTdez1XAQEyHbdoQgpK279z
mPiWgcbxUhTaYVnL6M4Wz1Y9QWk08s8X2XYjvt2cIRkgtgU2W/o9HrsFZjQGzMiPv8u/4QhDhlYo
Fa7pV1jcJxSU5sTf2uL4jgSz70nZSfx4Le3Z9RcJRscQiUnaRPPE0mMjmzZERXsrZSwRoOGoJLXI
6nBseyL4NP8WU9wqUBrmbNgBr2K1/iPe2o2N+EqrQFbZi4pSqs7aAslBBDheZxOVaZWCQwZuccBO
wRLTCHBCEq6CDXa3E41NOoxVSXXCn82+oNxhWqe0XdIYZchVCQyECj3TNb42Xw1e+EgFzh4ZExD4
MaARLv+82q+TSwTH9/Oo5DSEwImL12z3QhA1/Ty3EO91WNwJX6DCmZZ6yxQ6Il7OLRgWUgHKwzEs
T/WoZQzciKaq9mmRxnx4a0dV0xMmbWTovFVSQlua9wn2xjJKlt1+0uch9pCQ9ufrhM6uyRACj5Ay
QJaT3S38obtfEG9DD52Pu5Dpl8rhvisOCABxw2tp6dHW9mVQ0coNyDrI2BH5TwdelY0YlQc6hJPN
Al0omv8AGyMQxK8vkKA900Z0LRsjrA3ipQMryhidFkSrqRdex2a8PGt/m8ivnstat5rs6IHGae4F
Yy41WtSrvJrg7DqtWPi3B6q9NNLjzruY5PCaSg05U76OC2BgIv2TMpPfVBQbKfcw/YSEldlJ1SUz
M4xHBOFpeAUbHiYo8kSdG/58tNkCqY3fvz0qEte3KmSpXLNxIryNk5/K3Sk2SGGG79qPT0/Hxz/H
7nl5KlnHUKaKLj1t8rz3qxVxfS6wMmrjRgj9AOI96nHNMcuEYsAf/B2cyfaBaquAOuYPlSs36uBW
TITflXIh7onH4hDDu/OaQoqzPlO0BUFKSIn/WTfBKFd8jaZF4EbCcE58YVOYCMoZVYmfbK+pPUvq
D7Vqf3Xlb38zaWoakVvs/6xyPv8XA8vSUSfE2J9twmyYWs/A28k9TzmIR0aE6SihrTHJ1Wz3V74o
ZDBNSkhWemPyPz7tbVdENGtAy1JIk6xdsUv21w9ELT+j49beI5iCaVAZM2NtQvevyH86edXjyN1F
tky0J81l0e9pYmP+UC2UDterqlKwkxgU6uiTkAtaJ2vvFZcpqHTC86hI534VEDazZD37u/M4RJk9
sSkIXPHr+amJ7VhDNBC7MOfif/W2pegJEqTSH/xKbMBg6WlUh1eNv3K=