#!/usr/bin/php -q
<?php //00449
// 0 @Ioncube;
// 
// SangomaConnect 17.0.3.30
// Copyright 2025 by Sangoma Technologies Inc., All rights reserved
// 
// By installing, copying, downloading, distributing, inspecting or using
// the materials provided herewith, you agree to all of the terms of use as
// outlined in our End User Agreement which can be found and reviewed at
// https://www.freepbx.org/legal/
// 
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPxu/PZHd0Ll/ndwDynVrsZ5xy1NugtWVZh6uTtT8WF7j0ivzT6V5TAu4dpVMiKzh1/yYtexm
b/RgEqqY+HeEOGjCT8mSxGmWYG78HKw2RQaiI9/td/XgmNXlfY6fuqzRZ2EMNjkomLap5eLO4Bmn
nedpE0O6NydwRDPZkHCAIZUdol6SJTV03avb78Um/d50NIjsFwM9ZqZ2TyJMgIZRz99sWvOqL9bu
9+ysPsLc70oSA4Mzxk+Htc8lPka8avkawD8xbuGhfotfP8CqIUhgsAgExrff0WS5dcA+/pm9hDlP
lxbIrZUsjI4ZZTd9c7RscklWsYZkvp5onQEgVkOcl1uclzEEKj4Xn2DNPMGEuYBJ+kjUgU5vIXcz
cSbGc2HiD4Rs5bR8X5vPouqKwsgMeWyu1TJ9ue20KNBVBE/lMNC/h8FqqFEBPAAW1GMDlSk9wtcF
fvNlzeLmutCEoPz6GH68t+5RZfK63cZXrdy8Il/6MF5eBKForigghTa4DQnFzZcFJXTEQybZN17/
3OAtYrfPGQuaP8y+a/Rxd3rhRt9dbRr5D+YzhBHKr3KtYVm4m2YNTeye0bmNLEkIAsqe8uXhWK33
djMQMeUKGEibZ30v5AX5kyi2AzguuaG3UR9w7EV1JaeSPKGMesYFcIhuQrMDvBjAPGBHcvZF0xD4
GOG7NUX2QAb546LB9jKHoAPUmy1y1Mu7rbWlrx5f1FtqJtRtVyZo27vLBar6XDabjuajliytEk/L
dJuSxE2gZpZe7YZzA7P9YayZ78iAvamPkZO6IOB/wqrATfO9n+5665FuK7Tnnood/+XM2M85Q/x3
HiIqWaJ/rR86tmCzrq4kHWLJLnKFgSmuO3crLtLsYz7cpe2s6hLDqDFPAS8odgNGuUsvsLy2zalI
t8+/3NmBsLukvVy9sM1UnAwtx5pR8Wt2VCwtZmFfggkJf4q0GapyFdSFDuDgg9gvlLQ0fJN5KvZ3
+sDxTs82U5UFGLfnUJ9R0kW89xYoth0P8CcdumQBvR2zXA1ti+G27kjdCTSCTtRjnHrDaBJsHJWK
tFoBWfY128v//bSzIySkXxQL9rP7p9ocDYS/8LpAG1md8MN59nGD7pMWp+6130kah6Cl9V923+PJ
AUcTXBbXZBf5pK+cYYGIrBSmVTiOGmgh/MDeHelkFJPBkMrGeqSCTg+th7f8hG+tD5WZiYIFRV4M
Rt941brDn97ioGbT/+12g0+Wo+x5eMhavMLJkNMePeVijJ+02KXO9bgPEuEgg+H8dRzIr2N8OYy2
2rAMEVSsggpq809Aqk2Ig/cSjNSE3D6AHK9s4dyV87BNIu1/G5G18rXt/vgbrN5/kqKmVxC4FWGJ
1qKLyqophBgBL1cUE/huReUeqOh7Mq91oB8zdA41OljBx4/50qgQLSbKUpFIjHCR2tp88xZUhpMX
l9r4l+LFyGRQfG/uOvlAxYcFpZPcLKH4qWUgrXDFIyBWv+eBqdgNOTReonPH7LL5rUmgionpwiSb
fdb3A9i6U2mvaLArXaxnelMZgveEukPCXf7X+7pZR6lTpsyZ3fHZUrbYWrfcRCMRno8lYEZ9vfTa
iB98fP/vRuwhzizqZOMa3iL77CeVD7x2qzPFDORr0wXjwq1GMpCluFILhbvHipX1eBkp8VgJ1Zl8
wCmOyYxzcVVhj+jIed5Zhl99hC6DTOFhQJGAWrcB4qoU9J84Zj7LPZC0Oj5ogU+cTiUMxAXmt5PI
nXzjz561j0cZMjFTXw4RUUqFmFDRsd6kSa8oS75b9W1MpfKjrzZEgm3cAiIfKw9JRfZ5sHXB91dP
aNWjcw8DRIb2lpfS+TCGn7DpwfVjY/KryhbuYziIJz1iuEOEYtqU/106A6MpfD3EJXe8P8NRM166
8l69vdShuShn5bbxgSG82Kpozt77Ma8zeL7PJTi4CzhJ1a21tFkyu134JpBAJPlb67RCvnVX8bZX
TOig1FoC6mWhAxTTqNfkLcUZ/Lmf0ewA50nMFrVxwvdsBoyR2f1eJm6lbzAgSlyj54Nbr5dAZgFa
xNw3FSTV3kIUYEUijYf+6dirLigBjaB5tsiWFu8IoI/1tXyI8i3oD0Z+NQkLVCZFMQgCjFK5yRSd
kD2CRB7S0It3IhxSj3k35EQ9XpVLYvmb7RDXG9B32cuLbf7Ipzfqe/O6nV6O9xZm1Ps/mPkJC0YM
dfvn3Akfl2TxcqqCNs6pZcTla+dVsC8OfFRV5WJaT8tXQEqAaMRUD2MJs7+d/V79qY19FnWl5ey2
TMAs7q37CRMH1xl+1wpKodwBvxg9YKr77w0JYpUhLi1+sEsx7NjYMqRC0ANFuBXL7+2w+lXiymls
o39jkTp7Z1XZnvEhfwMJ3iba/mNIkXd/4nx1DetxjxzOrN/+UT9pk7SrFs89vYdv3PFIjmRKlKH3
9K3nXk/Tc9l+B37P4tvuY3FD8dOxAu5HlFZH0Np+YdlmTB2Xh9j1R3XVKhWUXM01ccGQ/sWJj7wZ
ZUGog60VrxpDFPEHFzrFaOVFjg1CkDQRv512EJwhQ6zmPKXHyaSgUS5LQkFLrg+xiG+FWSYT88Fv
owWKGeWpbX5e4m47bmu5pVAAZLhuNLzi54YZmyd0XUNrXDb7Sq2L7b7tpv+5zDs4gCxueZvnNaUx
UlMlhp/pUv+ydlb4RnT2rMMjXCCqLhamJJsDwyNSHPgA8NrWqmapCMT91yAoNcJ/w+O9f8GtbJLv
v+3nNH4ddD274RLo5l0kCpecKhnGFsI3fcfYmNUNyufvsbcCpwV5JvzxoHBliv/jw6s2RYjJM6rV
XwDBmhX4M/czFY41NpSh2tmFZd/iAlv09469mw6GSStt9Qrm3FfntVJId8LcK3Q7v0OM58RtWdVe
pqesuFQup/83RqKMzZewXD4c2GbZOo8ZgdW6ddezc/yAmrtFXmum9u8PvA7IwANHy/zSCkqJqgot
OcloqXQCn7WOyWEbb3MPl0EJHkxuH75cYN4bMZILhOXPRTMm0Xd/cmkldxPe2+Cc8ISrelAEc7CD
/texrSyax2jjdyPxx6s6Q/0xIgyL+s5NCoIuQT1V575/eVmSdvmuaGRc2E3MSLNhJhYNKD32EyAN
prV93j1SxkHmtsXTmG2kwFdresJ/2jHjL6UpqLb+otvfhMpgH723FNYSU7XhmXmBTTooo4L9nWIZ
Q/3MVtxGGwZ5EOpQLucV48M1A9J0452vXogOgrtjsUXCHQcrEGJ7M/2APqgaKRFF6RGsgOmm41WN
No4H3PYPHnJKkNvWCLVlDUX6xIrxvrv+ft1dbIK=