#!/usr/bin/php -q
<?php //00449
// 0 @Ioncube;
// 
// SangomaConnect 17.0.3.30
// Copyright 2025 by Sangoma Technologies Inc., All rights reserved
// 
// By installing, copying, downloading, distributing, inspecting or using
// the materials provided herewith, you agree to all of the terms of use as
// outlined in our End User Agreement which can be found and reviewed at
// https://www.freepbx.org/legal/
// 
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPuk8tXgvL2DTH3bBEKSUqgVJabhfcwZBqVufdJgTWDGN6/syXEx0VVtYS365kcCouXBeP7Oe
phmq1XqTNIlJeNnODFYcZfvRzsqkdcCktx6ReevErwJAtsl+w4EWxHiemuvvJJYB178zCTDN17Zn
YCn9y1s2Hbq1qnv+AWfibFnognP8hftFjRJUPJur6gWSSaA1rTSlze+tT98VeKNMm1tsLq2q/qg/
FoRPV+Wb/sUXfn6Pc3jLPivvR6Jd6PKJZkNxEfU4AwSjwMI3D4dgwjYgZk/TQuLDl/rXFX6taflR
EPtVOjWvQ2IHamgh55uhX5ZYJKHnVLzcKtkXQvv+y3/P+n3rJ/97jAh8PL6c1MflBNNkAkMZjTjy
++H0smF7CMg3fumnAiTIvDj2WZ6Q8A5TW/7louGVSeNkgxL/7JdG5LeG8c01oOQrbjUi1Yhla0NV
Y/6uPgt1UnHMTgqMBPPj1mCj5U2AN7KHXfISJ4jSTzhiodzYlTRGmEjrG+8xr2+jsGWnP+xcf5a+
LZuT267fDT6XFza3Lhdo+BFHV2PDj2hByCrD2pqrcayUDfgRtI21wugPgH8IH65Q0jE2x7Ocm/wd
QVaFJriv3Gkvb9HuB62FARnUtRPN/PaqOf9/Tlc0ktcT5xLePZTWSTh7Xj8pvk/pZzuPq3ZDba1+
WpO+byz5xbG0MLOom2PLPlo4TuZm6UMFqLu4SHrsQutTQPDbRJTJztVq8VoVwkxiFcmsTyJ5Q9aO
XXiBffyJ0RghqiIv7YgLRKl0ur/GVDwkHeZiUPX0auxfv413lMoTQ195cN9ERpHXThfa/aARiDzI
ES6BGC+A/tLGktwbyeANjd+2p1Figwwu5b6/1p6j8AWwM8iqq70rCNSveWvp6s/A7ow/vCVDMQ6D
pCc5u3YINsYnov+c2M5RYaO9TokIOXwS1y8K75lwaQLdVS4GgP46xHfqI7oQhk1Nku1CcGe9cZb+
1bCCNAKANq2UhLg9hOYILgKkcwpQLGkjaaN14KuF4dPeOPnx2R2HpJ6Piw95SSca2OcZqMd3ryb2
KDaaM/Kq7HadPBlqHzIbCnriZ7gEJcuXUYCks6URnrujYOP3mSN/PBUS+/UvIDCFV8AjgR8gswt/
Qe39J4oSLdR16Iv/AIDD8K9gWkuKlypVCA1NH1RzPpVSzWEQjrCQphxgJATEgL4doBMC1EB2LhLF
pYz5crPkvX2JmpXQQM9hH2u0GL0378S3y6Yy6/7q7WhMxKqNhcd0FkRQoJslIWuVZyx9VjiJ43v2
w/9X35z7bMvermcURAujLCAEaD1F/6HbodkD7L4cpdut4yvM5baHl+1M5K9nNyiTJ6rUNHT/7ukY
UN1MRnHdVsdENiukLnrUUXKZBVq54c1jgWSwEo1isz3Mxa/bCH0t5kvz/xxFfoHhRGCRPkvMfgO9
xrt2pyAv2SySKwPnadKuEXfIfK6CcsAJzjVtG/HUlr71OkO5MiPUGIpU0jfG0tWYtraJBgrjzlAF
xRQmnJf43LAKtP3nRd/wEVTjS5AY+J8j9kOiXZza16bDIjp6o3kHIY3XH6cjZwPVWFVUblCuDIaQ
N5JE+3zirlMCfrI1Y20p9oSO2KLfGv+xEJDfr5PRiEDniK+eL+mt3cRmLc2EoaShI39tUqhPvOqz
MCa/qzjcN0q69tRpv7eDybPih0uhO2OH+g3rFzaVH7QlTtv7aQxjXRCqfWfsVY9CiW6ZI7+GZJbF
cA9/CWFN911gYzUMiuafa2ZxDfNz1dGW6r6YaNnjVBcXd54fCv9iudzuse1io8EJdbW48DRDSSon
x/zETujJRfwxcSB2mvQL6hRceF845s5FH0AlMP1EWUC1vhNgzV7TYSgyFTcUijnseUWp3YdE584c
jFvMHOq2dvk5yntAfptU96husLDN/LnH2pgr6ei7TwTmj9IgMGmKhk5IboMdCJqdYzE5TR+xPCpP
WHbdkpMXReYjW/8izSgKm8dBrNIb94tcmoSCOU6woaQw+MFokdVn34f7gIvysc9ulm9X+oEcImdC
vqDqfpHDeXp00LbbDNwzzGZkHwCfwYbSjE/ufLKpHOOc0sK8xl9zeETl8PpLIsPrbtgDdeD+ffLs
liCxT2tnucQZQNgsQTqY7A1rhlczckBHIIW7SxfDfRs8+ufKhUSMpnm3LyXE/9Wgk8ltv4CNERdP
AdGrFdHTfHBnEVe71BGcxgRfA27VuvI5+LWGNi4GwfD+jM9nFkzako5bjvp2MjXvciDx25ZHMGi1
WsHPMrJt4e8wa70xXJLzdoVn0oluUFKBzzBfIhornBTXxHVZRMyiNgOwZchsMSTsG7MQSw3ZMV5E
yqxybKiUNf5f4rClthNic8WYwvD9Z3T6yCP/7uJNUuCJssneoVc2Lb4HgaCnIUEKrr+Afj0rN0Ei
7jMzM44ZSjZn5kOQ6A3ErtgT3eL/iEPVRL2JPofnsyZHk1BU7/ibgxdLo5sYlHkJVRi8Pl6s5hUw
imzqezmY/X16aMnGSWQG50l2wTMXD37HQFY2It0S5CFRo08l0RUKRDDIgqyg1REVB3jw2Bhz+FUb
6OWMEpveXBAQSTnZZjeLjKK8U8PJ8DXJL7oWo6Zl294YHdkKi2JmNhvnS35Fqj14lqDGAqhHm/t1
Z8fn5JFxPB2F+173mRlAhuiO+mVTGZTVSMoG0S0p3lhJozk8TdTRnAuMGE2rM6/FfmZuf+VSRQ7d
2dHtbapS/SWgs7c1+GsX9rq+eXXC6s32YDI/WIrfcyjQEEgMs7VBfLJSIavnfcVVQayx3sk7Jyx4
oOfPWYZNktk/QdR0MtltIN7uyZ80f8qbseIMpp2/DloUGGRQbMjDNjDQlpXKK4Af/X9AU97HB7Hm
M6cft/cDj7KEbQKR9JqtNnFUWO1/qDS4VkihWGSUYW55GgHwnZc96wR8oemD