#!/usr/bin/php -q
<?php //00447
// 0 @Ioncube;
// 
// System Admin 17.0.2.33
// Copyright 2025 by Sangoma Technologies Inc., All rights reserved
// 
// By installing, copying, downloading, distributing, inspecting or using
// the materials provided herewith, you agree to all of the terms of use as
// outlined in our End User Agreement which can be found and reviewed at
// https://www.freepbx.org/legal/
// 
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPtQyffidXnlSFWipkFcua99SC9MtCMWtCAQu/IrRwOmF7qiPyTbRBfYCgvqblCD1Q0Dj2zY6
cm+7ZDezRQn90ATh3YDDTwZrh344y9hEnRiiSYyD1WOqMv+mx6igADPh5eNkLajUlyURVsXLtkrP
//0l3c/WD2kWn/qdwBSVXmky1K3uZxygcXBkH0wb3YQ7/onBRKYIRmJZqrh4QR/DtNu3OuTiWRhV
BuhtcEKGvopUDqKDMI/a+xZDApxIWfdVPbZ3/GUxUcB6oNt8HjCK24TF60Lb/t7WCGeNBIA9pEKY
MPW49QKFhYqFaHyvpMMsrSLelRF2xFlnX0El5Y/Qa+BjGfgBl2FtyUc409C0b00ceJviJNLpW0Xp
0VIvNceiifWsYarmFnpF50NP3d6vVmicvhjPzT7CgEP5OUrFHSuWa+GPI4O/wKZzYJw6Bulsi5SW
jbhooCBki7FLXAusWmCKJ9GMFv3AjLeOwWn81RgBvRH2c3bTuUkeeHTjxYKUMVZVtXkncRgjqlgi
jasDm9+5yUfrtgzGS0mo+Nq9CoXejvvOB5CPRG3rdi+f5geAcc2FXd5e39oV19WaA4YOhRlzZ8Xf
AoWzsuPNFSIxTJVPc/fQ9S45a7dZZWT2sPhHDHc7oXqG72bIV1je3nIYOF/vV1OBVGUM75cLO0Dd
OPy8X91kwPpcZFCUbmgBy1IAHrNPeCwIH37/wcF0yB86WIJPukV96y9ci1QGvd13ABwxuYNyQta8
eAH3bEOrDzYWamJozdv0y+jdpPEMp80sMjVONs1OiIjoTjq0et6485XzDl5hdA2ZdkpZSZ0mv4vE
eZPZYpa8dScMA57WBitMMESIdoIsDqBTto8M00/cDYNj+XecqhdGexAN5HtbyADDH1iTgGaJCekA
A25BW9ssBOEXMRb10AY87dbrDeW+PvQO9z7H4EzLGr7rOqkoL8YpLm/UlpPGL4/eiKDSFyNwzHcC
EZl2Q0gqKbGuUxPTgLmt/pucOXoob9269moKZSlyNUTT1UrP4YQXkm541ZiMhbB8TktS3LjJutBC
eI+WS84kAcpENRdHFs22MtCk5p++RZP8PmY8GqXmkID+NIgAzkGR6zsxIcm0Ra9dJBQbe8JCNPRo
zhmroMCCCIhsBG6Y/0aoLXZfVPVV2z0WhNKGz2aKknqj4oKcCT+Fs6wWfAkzvC7QvzgbxILdBZL0
IPmQHl9Q0MS7o940Qd6AOiHwpfDFei/edTmjRNDQIUkAANvXQmrSOOEKvgL1ydWZ2E2oAyWhyAyK
YvtJNvwRC1LWD07E+P25klWLNFtLIiSRQVgFS6MNm1hcyhZuvR1BVmedPIh/A4A6IJqTU5+JU2c6
ZOJg02NObI7JwqAFrrF9G0fPDapKtFhly8o558Op9B2yxkXcksCVODTebUkbuHmCIfvRi8pbkLZF
zba4V0AMHQzhxRUvOLIVYOx7eeqM7xgFMYS5at6ddmWFcm5MlxdxnKR6TzxLu1wf6z2k2n4Npg8u
ktdWzRW+80Lj695xP6Iog4eboFLOKN0DdJun8ySLs2/m0SACL6M4rK9OjmU9THnGXA7JelApuEdf
PO+n5e83RDk5Nk3PPY1KFdq8LDc5C3MSFvZiCMwo9uoH6ZRCWoQ2zC5rBJRv3u1H8JcDo/9kk7Vp
BQ5OttrKQ0CPmixoTSjoBF/pR2qKfWo5t7ib0s9+we1FnBCZZtrbTXY8d7DgVU9dx+pEEe+IoFu4
pvlZ6eIhi9+880a56aK+2KfgWEcdmj8mMmxrssR7L7zw2fbUrwNrqEybwkNih43IeyiMun1aQ6vw
hI6cuG9fRr4Kjo4Wl/HSzHdmwsNcUFsY+cZB96MSrlwXJvPVkR5K5pfxDVL7oqXfJGlKU8JtqBt4
uxbdv0R0ED4w2wRR95aP+ncoWbkMRf1xwTGFeHe44f7O6NBoPHXhp+ugz15b99uQm4NyTgiSeFwf
WSvj2FedVUq0k8L4vGYaYheTWG8siVVPfrFE5kTY1bhyJsgooz528exIHISVi3+isEnIMZQzoaoI
hlZswivtL/aW8500Qq2vfVhEK3i/Ob3T+GDfnIJtYltw3ZPI5bMaIM2xR0NwKwPJID267pQ1wtQz
d4oxmf/ZBkyg2pREiy9kxm6VVjjTNY/go+P8SQvFCD0/8XWuutJXmkLIE+OMOz6BP73vUE2/Ytx7
bfZSj4rhE5cuXNLJZf87JBziWaDuUEDlT5CA3+1IJDa5MlBhNFF9qhEWlSt7lf8uYSJtdvawJXeY
zoCZVGW7jEwv7Eykk5JIKDGYbxf7bCM12ORfgs/7Js3UWypfTQHQKmOt6reqapwWalP3i5rzZasH
OCOhtRR9VDvEQJrHUfFVNAV7iLyfPiHsfQIcAWq1t3Gn9CgDS1Xb7oOk4fbDiMvcF/LnOnXKTW/6
88epu0Iok10MUm==