#!/usr/bin/php -q
<?php //00447
// 0 @Ioncube;
// 
// System Admin 17.0.2.33
// Copyright 2025 by Sangoma Technologies Inc., All rights reserved
// 
// By installing, copying, downloading, distributing, inspecting or using
// the materials provided herewith, you agree to all of the terms of use as
// outlined in our End User Agreement which can be found and reviewed at
// https://www.freepbx.org/legal/
// 
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPvcmPamrdbjam0JpRoHEIPLThRWXjgxVsgAuL/qX9Z31ld3tGAmjycSoW6EiDfNhp05COcJK
3rn7KTIUZILcUUbqhO/4FVIQjuRkfMze0nVeixCraNeknA5wE6wg4yCVH9BGA4dBD4gFnSz8lmTE
/I/nL+KQVCx9KARs12cGtXBOtcfLQU4hSpzbp5efLoMcLCSHCwQ7SMLLW40eC/57kEiE67r3Econ
W7AsW0uk7GPUMCGxiJvxt+fd4eyrtiKSBXI+/GUxUcB6oNt8HjCK24TF6A5Z/dnTrj2s4oFSlpM3
mXSk/+/sx0BqsqaV9gWc8TT6L2yrOKikbufrNhFyurclwlpQIVNqYUL82m5BOZNt1XUL7cqiyK/O
sb5OyxQhpyl+da94VjZgJBJlC+VG+btqFXXBRXCJdFUdmHM8qTCcChTtaJ5uHhKQRqYX/ZA2i44U
wxz+oaMovE0LzjTmYzRcuwF1xtL2MM3tsE7cKJqD7BPFw03sccmt7Mk8SPWWAbPV1SYabm9KP5RQ
QwO0WH2iyWfNmpaFucPUv8HkZtlQMH3kKgZvljPGLokTQ2iXDXmXz5PhHiIP09Of6EyW6RGrvt7/
FzWUzRM7cRrLjqNFePrH8uyRY7r7k+G3EJRezndvCHp/vjPLrzvZqKJ+fGnbPHmCJj17EFbx5z7F
xCJYD8DYMcn1b/NZFeS6JrP2bVp/wuspuGmmDnbwI/e84pE49QzkvY6hCX1GPbmebElqCxPJDkRs
f/zdNlnTHkZgymmuZEnBpy0I0Rq6wiSo+86sa35/eoVhfc0/Zym9487bXMPPJklgbJlGMRhEFGc2
LAwQ5W+VTrUQzyDEva8ekc0rQlOww2vXUAOCEocRInwaNkOCJOJbLA/P1iqlFHRuvw5TfqtXZndF
nyK3IbDGRmG6eVbzowWvRBknsfnWumzdPfnTH49vKniAw4n8XFSUkUmC1I6bpt9XlPefrrAtHxz+
Fh0sMsP9tcuSL0h0u+B+CmKz1476zXv6y3Ai2hummM1hjRwdkqO82W9oHvQJrKFK2YXS5kN0W+68
O6YgWz53AU5imtHghRPIjtfWMNqYSDIrV06y5eskIT78VNyiKEcBNyRaBrri8syZH6gRy6kOP6gy
wfyG30dk0w4mgBZ+PLwa3Wyq2GvNWS6fosBYBcg9g4/YdLNM5gds2QcX/YxM8txadX7yuQ12QDO7
5s46oMhnYi11fbcJafnwVoDtayD9fYwDKrZL4NeHVwQXlcoRa13XetVDIPpiVYXHXi4tb0OSYLP5
ewsY6nVxgI3uIftMX7qKSQyp6kathDdWNXBAQOJs0ZP1faXRA6iTaW6xvBrG1d67Ck6RADGd7+Ju
VmwftIPTFqqIYBY7MayiX7IjnIAsk8/NzW==