#!/usr/bin/php
<?php //00447
// 0 @Ioncube;
// 
// System Admin 17.0.2.33
// Copyright 2025 by Sangoma Technologies Inc., All rights reserved
// 
// By installing, copying, downloading, distributing, inspecting or using
// the materials provided herewith, you agree to all of the terms of use as
// outlined in our End User Agreement which can be found and reviewed at
// https://www.freepbx.org/legal/
// 
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPndVBIy58PO0q6su31j/DOLnelmNDGNfePwudRP8Q/+kqm4sZp3c3t/FTpToOzVnM3/O611H
U7m0Nh7jHeJ2slrCSPMPI0ooL5t5JGmQmT9XcJLsAPszDL43l7nR0QdT2XotlxeKNR511lYoWSvL
hMXiOvBPK2OH+6bbaFudFxnPYj+4gKxd0QMUcpXdjSImECW92NYPX7obNP4f/5rJAmcj+hTxzv5I
9HOJ39jf0tyIrWas1EMRw9th/j9aL+X1WAmz/GUxUcB6oNt8HjCK24TF63DYSUbaIu+AtgpnukN2
Ro4dwxKH9ZCvehK+oN3HWx0aX4fPdqrcL6P2me3Rcg/AhO06z/ZQ7ZQXyBqgdnXOHIBrdINr7byk
F+yBDPxqMpQRYqlFRGHQEh0bJ3bDEdz4OJ7sGgxUyVnfSq4ux6fiklST+vdl+R+wNpKLSyT9aOI2
KE9u2U34hePdemQb8VdPmrNULdFVgfPAiOp1VgC9CF21f0blfrluc/RHI6AhjaxZnV+JQDsygugi
pub6lq1u9MOBvt1UQhd0DDQHzCpXX7MWwhzQw54VUQQaA4x2WJaEK332Zd8UGf04GSXKPmE682W/
wOVLddAXArJS32k7758Jerul7elcuYH7KBkJftr3QgpX62N/wnfNA2e57wYrZCQsJnEm1Zw8+q/n
j+3KjoBtKm2MnW9eJzFj+t1Cy5/hfswtknx+nkQrQpzYaBxxPcDsDN9RtqGB1dKjufsKl/gxHYLb
rZGoiztXuOAxuW7rTILlU8Yk1rPWM/yANnKsuSNQXm25mkWhv6WwZA/yWiQ2W2MGB1gSFomJ1IU8
gWydtehsnohhwtRhXoZ/8b78ZbAKvGxwcmiCfLGU6DIeVt3ilYdoKV+5hQO2/buanR2r8dIwioV0
j4HUmubnqrFV8UdWVjQmxDqMNh/MWbg4MTgLT4uzd4fOdb9BlPvwabmBxnckMX+RSEFQB0OedhQ0
HhhmbzLj4h5VpSEACkfqg0i2fKwVyQyhRCF5SHduuZVx7O4xEg4KPw995rBIOAtw7ox4d7I8S2Gh
cb1fT9lqWjNujL5I4oQV1IPwm6JWvuM/nX0zN5VwP+T9N9k1+vwZoOkvIGs5Kna6TxxFBMv8qsV6
IUP1lZPFzjbXaKSvwsYVJv5y/yQFwAhe7qxjgvkAiEaCIsSxTvSa1Z1JuB0erg1K73+vfAmhcIhH
8isIC4bzfSruc7AOFM+Iz0XDwngoezzCM+BTgYtbV6tTL6I14uDh6+QZu8/FNrsTm6+HO5EGp4CV
JTXzbscOfGjk2aLQAmGlbOoMnFrr4nMcDUPBuKTsPOASUpYdIlHd/vZeZVl6Bz4WXHpnyfVl9aZ4
C8EEycyIPDLaTT43/utHsReT0IxSMjgw9uI/QUZZXw0uHy8F0ieYPVdvA4UixQ2OKZB+YPYegxza
1nw37A/ga/GQd8Ox2jLuA2i/7IyVB7sssG7/AL8J71fgANQ+GTKulY5Kj4GOW9R724h14lEiYJ+P
vmdup/7J7YL1lJO2OWQ1k2qJk/ZZkNCDRE7c9/ZLJGXx4JwayGLnbo9NfD73Ql0eEnKFpf9psQ/5
+f41NfNe3Cu6UVRUTCRp1s0TzmJAbvTC7cMlg5V4YaU0sbbnioyzByEPDPQX5VA17Ab00rN7Wxkd
2Lebs+5ClLAC9Zh/M6xBXDw4ys8kz3acG4783+DxbNLrWyg21SR6Y8uIWvWd1G5znyo8fxndGNCR
ykh9mqgCEpd2sVCSQdDZW/Ui0znyRRE1oC6P7M8nfAt0bTErhti1s7r+sH2n/l4MNFI/jktfBDwZ
Z7aYtJ+e7a/nFmgtjBRsW4K3bN2A8usll7NSQ4I69/XbVMlYHuf61swIby30E44pbvRorU2fUv4W
tilb+gZgyQ+Ssp33/g+x8trwqkpdsdHomUiYeZaaT4cCr7PmvLFiSytTWplHDWM0XmYHuBOZfIwp
OL9uBulDo6IYEBbf70+oi9Wg46F7TeA6NGGRlqzLo892l8rw1KgUU6zplsGUVO65hMF7qaWwpb/F
A+6jeFEzT89zKgoKhrBEa7wsRHScnuupcadB4BpKtweIXVsVC7ZVM6VNjo8xnTqSdWRdmm+/zyAT
K1ixeVqWRfqu05NpdUYXR6rGQHVfJXqbX9Yo71xc+PgiUUJz4OUO/IsFzdRBDEkTa0m2EiVmQzLx
Wvs4V8djtkBaqge12zOoH9isOhUOXfq2bPhkQvw5XKtg3AvFP7rxca+Q9z13jRU0lwNB7VtDQtch
8ZFWDY3b5T293uaIPFD/jjD/vz4J9CyW1LQD99q6K7Cw7N0BSCNLlIBZHPXrdZ3IWcG4AbFd+RzG
YVoIexVh9XJoXXDj2qjRp8qV3GXH+NIZDZjvlqnppQ3BwuEtNXbXNYENoGvCiu3q0/OoQlrGgtsZ
e1qp0/qayby/XCp+3A1ju/Lo4+QdLrB2JWqY9M5aNhOO3sGcd1o2U4wKM56QQryo6XGjYzFe5peH
nAxEvAsL/geQQr3IgjUNKUiAR5KGmpVyVNK1AJf+tolCZlTBXwqkXGWA/us89BqKtlZjbVXIs8oH
oHwKtQplLkUpM6yx8OHArY4Q/+n+74AdlSq5P9CrkTinxEeHXfGTujDIe7/kB9ghfPkn2pAQuLMW
v3GVQO8hFOOm2lcGTFFyn6SfbZ4bDZf6CfZbOSf8qD/tjIZWYJQRf85ks8JUwd3/e7O8tT2tGVaB
mWL/iQ5HQs5jJl0j32ARIBeSpR35NKi7EKNlq6zf5iJOnPI9JmtFoCuqFgPdksAoKXJ5hAUuroSU
VgHDk+NRloh6PZCw9nOGsEwjaZZFbpTJJyOjXNMr7Cqa6NG6MOsZH8KDrtIi72WT/PyZTrl6Sw8p
98BebKGv67duRr3Le7V0KC/sAJLHRY9y9d25Vts8Gif0FOkNasdPAQzvWxkTNNzMQEXyVTEKtqrC
f8dxQuY0MxH251OeaDbFjwVEgeC/SzDJmnchiX/xIw8+hd/gwmHGsQiIH5mwTdq42C+6IGD06arI
QXUw58ukI/yN17lpX9kqugvi2P0Ne7nNalZVyk/XvbqgQRAaGrUYuQu4hbp15fMcrPL8DxQsTt1f
eOu9+ED7vEAgHhkLdtwL9q0rBz9/X7DIA4UHQ71G7yoXQBZ1WiMfXIw7K6/BgnS2ZNh5FXvcpXV7
/IGMhUe7CbmfJkidrcSIzYyN5t2SVLMgqhq4RhzyITQV1TLc0vVVlqxinuM6rUKEs/Y9bNWMaFqf
vaG56sA+IpPmdInNqEtRJWZzSQ/kOXtf