#!/usr/bin/php
<?php //00447
// 0 @Ioncube;
// 
// System Admin 17.0.2.33
// Copyright 2025 by Sangoma Technologies Inc., All rights reserved
// 
// By installing, copying, downloading, distributing, inspecting or using
// the materials provided herewith, you agree to all of the terms of use as
// outlined in our End User Agreement which can be found and reviewed at
// https://www.freepbx.org/legal/
// 
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPsMW8QtFZPg2bX6qZax2gTjUrALak1SFXhQudMNV/+ed/pDyvd/M/96dsgPE8skVMWijLG7f
1YT3E+Mjky2MvOtqBR7RtQCYry9XvrEqdvmCdaCr9ZZN1pA40NrOTxGjb099+dNOsdH14Dtuy3AP
HviHp4gCTv/+U7uFIHl/H0Tj3kW3JRH+uMqKZDSDG9BtVs/DbwNmzZBzmpCwb/ARUjuTxDYw5M1E
qh/oq7q8+GedsqSpB+B5a3D7Dtj7udA35zVX/GUxUcB6oNt8HjCK24TF6ADhJYxVQrQViwIqWkKo
3KiQAxpp0iI3ddKBFVzjbf25b0m08yty5GyW5ydMl+lm+LrpKt0lLlNpINb0Y1EQ017JAGrSNOR4
tP6n3fsD3f/r1wdvc+k+0JNfrYdjGffglJMv2ARuJNnlkqAFAq9l5LwpYJLtmExWUqOfgYspv23w
HYs07QoEG/rCDjzR+iflgpjAVMCEx2AEJYxDWOagR7vOYJXDYU59tMKbi+IRvwS3fwRvoWjsnJFU
HKhzqIgP4bNjuasxtjDlDEEZsM0SwlaAY4pFAhHvrq9KRqnZtoQhl+hbxvGxkhP6J9j1QUZ48XGz
AClKxCtpMenVxnUO7lhC4y11xREk9/aAUNLBUk/oFkUOcbB/IryOY7zyjqUk2T28tkqCJXv0bKWw
yqGqLvmwjJRVtlqbMQ0YjPmq59htd66Z2iOOi4/bfRoQ8tJkYd1eRjfVYqzQVWjIlgnkStScA/vS
jAS6rs5N3ckq1bC5aOlLVAcYqQYNpjbixvZmpcf2mY/fC0HP2Ovq6yox/eGCQxGNX6yMepC4jaHq
UERrROG3+DDt45E9R4m+mZGPUIOMFqMqHDePkiVJbW/NEXOhPcfqMx6LED1Q9l/tvl7u92pFxgxJ
zHI4gvGArKyfEXrlr5UtuHQpsIfzl5WerKiLjR6SWjpZCNlHdIoGX1OWC0y/fiMNqY/B1recP37c
ir7kgR65TIdzBSUlJwltJsRpPeZT333lqQSbiHLNJfUYfGGBhtvRZ8gKbr6wfWMKrfM/KTMPrwb+
DoRomU3eUDYdMx/92FEcdaQyaLheqd7oeBMoR2Pi0qh/K2Q7iLydxFmrR77DTKgi8VT1vzP8xzCr
K3tQ6FK2un9aJoexYClU/OaWzXVvnynJ3luqdHO59vCGNhfdmmR0mjbpVd48l8+SjtLOKIe46Cmq
e2p1WIyYqxRgnmQsodgrfLPYkng+Z2EyyplwgXm0zsD0CrvlEecb95t2FKdvOw2hleIAC/a+Qaiq
jqLURZxekEsOoc2R3k/oS/B2bHTwceIwb6zA2uxMV8TaYDTj3gux//LJ5BCbImZV1qcnOl8siHGJ
xDiQBViQWJqIBApwgs5o/ElP6aCMXMYWPoPVZG0Q6SEgNXSpZtXBMa/+Elm/tYbSfaukHCG5r7kY
r6o5uX2p8hdpjPSOtD9SYC7L4Q6JSki0K/O0CwSEu3tnpiHMvVeXeCWBlVyxTrCOC0gPnPbyZob1
QFun9Y/lCljcLOTIyXb3fCvWROm+CBBSZFeplxkS/hR4wdkxrRca8dYwGEcNfDsIUZdnT1fEWkdN
IEo/HiEXoJDkEslOCheUHk13L1qOprFS/IlwsRkFbkpEdNrZBOAhyp2iwLy0o4+b1m9pPyXfSl/J
NOSF0/NkmD+YbImZhjD3aZFGsumXksOiEB6bJDeFfCgY4U3vWpKw/9dq74mUX8YCa6SCqNLSW2ZX
v5dZJ6qVXo1RpbIKDk1TbnBJFjViQ7xrl9/IODJoWfnvEPPTpPI1bOqBY17+/er8LHVIp/4Y6cQ9
OW0Gn2cfI7mSeimC/IOzi5yl6ruAQGEtn9jimkn6JMBpA0lNbw03PuBVKfDOVO32dZrvN7jggvlN
pHKZNyYi/MF5egSde0EcffPYwIk5SCB9maHz7wvG9s7tS5zjxtASysrTIcjByqikYFbrM8hxdft5
Frod0T455uioxFUQr8MmQhc9P5zoJvV/9IIDfqN4RXu+Cr9u4H6euyhLQuXjEYpJrDpM9+DrASJs
DynLQocG/WEuvd4MOyNg+XYZz+RZjS80skLc9tPvnd0sh9emVz8W4TvbuP8SXOJEhkTk30DH8qCz
GQbLAG+tXU6Waz4fpuKrqFJKzBZbunbvv1G6VmIR1vmh849jr0Vwa+GkrG88KKiKT1yXm8Zie4KT
o2uhK+gwMbPSwbHjpw9iIeronMVUCUUyfLF3VpMBlxCPZ6XOvjQwdGMDPR9QLNSO6vlO6hiOaQKW
OZNty4ib2EUS1W9G9uJ5B/IdcYsV03ezxoX/EkUvqmJGG+VEB1eNJcTFNJOxHgqdsplflQHXtg5p
EKL3BBplgTFwjzc9yzaZlq6XHvTs/xtNGXEEzAaxW0NTZ+VKIVQcTIOX9cptnVsDqd9YUidI3jYs
pgH/XeEDWWst0uSYa6hpEoo3FwAyHjXCQXC0trg0wSzzQvtVwHttafKLnyHEe+c32mpEVIuVCcIp
kCRwTInVSReNZo2cQWyL3oqisLIUYw1xP0leX1r+rsywE4DZfh0RmMth7dTdB7WGxWB+Iu7JH7O0
qd9C5Er20yEuZ6n9RTnljHThTWbTtg32rcmW+LboZab+bbYmsa/W+Mlc1Gyf3ywZ6WGOI6BVlyYe
6nKC8Y988DNSBJuiPyYiHip0HDNVBU3ZwI30l4kSIVF4U1yG6U7EorLpuWhzoUmeAIzz+b8JQDk8
TIMQ6KMSXE9l/b2BVzI0O0O/SZ5K/P0ed9ASjjcuVqt71Rzl+saJPEL4gWYvE9x4A6WuTjVTpltK
thiWHiRN/5ge7rAu22/vD/4Gv1Dy1XgKqZ6yFJWksTN5bLHJxVd/spfaCDWnHMyuWKf9oypDdRst
SW8hoVIFO3qf0kVVXTM276puEENuwTKtJxY3FGVIwJzwdGgAFV/JLca0dx9I9/6Xr8cTeNC8bQUA
RrXqVp6JwMG4rTIuURyVxeXl