#!/bin/bash

# Can we ask apache2 to restart?

# We do this because systemd insists on doing a
# graceful shutdown, when that's the exact opposite of what
# we want.  So if we can ask apache2 ourselves, we avoid
# systemd.  Sigh.
if [ -f "/var/spool/asterisk/tmp/GuiUpdate.flag" ]; then
    exit
fi

/usr/bin/systemctl restart apache2
