#!/usr/bin/php -q
<?php //00447
// 0 @Ioncube;
// 
// System Admin 17.0.2.33
// Copyright 2025 by Sangoma Technologies Inc., All rights reserved
// 
// By installing, copying, downloading, distributing, inspecting or using
// the materials provided herewith, you agree to all of the terms of use as
// outlined in our End User Agreement which can be found and reviewed at
// https://www.freepbx.org/legal/
// 
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPxg3ZZ0TQ7C7s3OR4omdivqEnPPOedXdrBAuTZ4/fCutTknwnqnCr+TR4KioNfNJz6ePItMW
Cqe0cmmOyj6i+KWhK3yoQvcDdTPeJXfhEn7Zt2icn397DATMZ9LYj3Qj//HGYmnY2m2mMCQpKbUC
9Yd5riRN2lj7jGPNYLLeZMCoiAs1Qv5PhnaMUg+qROBSJa9WjoGntT1S2hD4bEhZ3OvFt6nWw6dO
QFOpA8LeVN78IUkPC0jWKpC7M3g/TKFK6RBW/GUxUcB6oNt8HjCK24TF6CDWQNWmN8cTDjfbzUNo
T4ODFnAgO0RthfGNsc3tmdCA1QziVJjWXH+Y2sirKDJLbmqoNTbBI3xjnUcbDdRR5EWYRmGOZc/D
tzfhZp0kriqPbuq6VxywvXj8riPsDBanrt3EmU7ZMvkA8goe8En+55eCgS5Mjm5EN0Sl0cP2Cbs4
WItOeiBylIsDNH0EhJcV03N6hxtgBOOJcbHw9Dd0Q1Bd7RUQie57Zgi0RnWe2IUE4IYmWDLekxOR
fDeY+OYDEbrMzH7W8gRcNMVSHf18qMpoqGO1ng0EorhUDw4LkzDgNwZ9X4zExTfJExJVOiS9T10k
EhDNaeF/yWabZlo2UpW/y0s/+SoZglH+glr4W53yrgiYet3/P85RaJksrR71vbHkQDGGB6N2ieqo
wYOn5iz6RkLDEiZ1JKw8VzaNMYCKhwOt/qGIlkFqYAq4DF718hJ4CT4w+OMOHiKRQDjcHfmbrSv/
wlKNSNnwu36uSfkLXoAKWBXkRabAArhBysVVfyiNqW2uLeYqfeB/mTzfUYQoaiibMx5zs+Us7mLM
gxWLJCH/j4lRbVZeSIs84+10JkUzhc/uGI0D05baNnKkyrkxmhwA1dFOCvFXqUHTMeoQXXT05Zba
vW0rSkglDYX6hLMJZIrtSHHwjN955xg8+TMEhmSmnRF6ZY1PjJ0eS7/H7v4jxzAk5s7WUdRnhmkU
WxA1vyVA7V/39H3912MchwVWWLg4L6nT5reOd2SqMZJTDz6SmfJZgjWgpQLIgUjHew1NqtsYwMK4
4EotxTJ5nyu3oOcBaOa46xV7/KFJXP6e/7s6OXHKHgXwrz12Ze5Jshjqqlcm38wec1P/ODA7W6vk
lkmCkclmVzl2dmXSZiEQJyaT/Dbowt1Bef5gxW5M+9iZLUCAdeN0zWYIXfDXgDh2+d1+RIe8RQte
U+jMyUnF/eF6abye78zeCQearjNyMpEOmitmADX+2Rs2Mf6OeywTybGj5mJIYJbYg8UhSRXdmyy/
S6LyLCAJYqFTZvdzAdjgxHvKoKgqU/7i8Vx1H0V5N472ZMelefrpdyW8ZWF0q24R7c6FNAOTuL49
kmufVEzRCnaQSzQ57CWwHJ538a+87mgOd1BrtRtWC8ZV6PLCyq4PvQqJQmIzBLuwRl7OIUJ4sTgY
xn9RMnv3hJL0E9yuoOXALYdZFr5N+uQO5+SCoKDOn+4OWnFkkQ2TQ8zTGtmF6MqgMg1uB6Ro8MFx
PvBbVltJrf67CxdwwHfIutnmelzXM5qr02ZrA8+wIrnFTtJ8WTY8r0mXLTV/GQVu8QN4O+VLCKua
6lp0dEb5qXcByYi1tc6+7I3WgQ0eyNlJvHkynQBgwlVQiYRBPikWTL635IbSiRDPLCzVbLpQUcvX
OX1yL+MEjGr7o7fPJXd9cFKJLP5UtXgM5lH1DQT9RighWdAHWDoWz/vjAjDrBkznQpEG/Rlfduz8
awJBagQQsAfLJvUNOQTG/qOj7arkBCTjSKZha7ptzrPTRY7loyDZSXvH7mgi4JWt90==