#!/bin/bash

cat <<- EOF > /etc/logrotate.d/freepbx-cdrpro
/var/log/asterisk/cdrpro_*.log{
	daily
	missingok
	rotate 5
	notifempty
	sharedscripts
	dateext
	create 0640 asterisk asterisk
	su asterisk asterisk
	postrotate
		/usr/sbin/fwconsole pm2 --reload-logs -q
	endscript
}
EOF
